[tool.black]
line-length = 120
target-version = ['py39']
exclude = '''
steamworks
'''

extend-exclude = '''
^/\.git
^/\.vscode
^/\.github
'''

[tool.isort]
profile = "black"
skip = ['steamworks']

[tool.flake8]
skip = ['steamworks']
